stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/locksidian/locksidian:$CI_BUILD_REF_SLUG

test:
  stage: test
  image: registry.gitlab.com/locksidian/locksidian-ci:master
  script:
    - cargo test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - master
    - dev

pages:
  stage: deploy
  image: registry.gitlab.com/locksidian/locksidian-ci:master
  script:
    - cargo rustdoc -- --no-defaults --passes strip-hidden --passes collapse-docs --passes unindent-comments --passes strip-priv-imports
    - echo "<!DOCTYPE html><html><head><title>Locksidian Documentation</title><meta charset=\"UTF-8\"><meta http-equiv=\"refresh\" content=\"1; url=http://locksidian.fries.io/locksidian\"><script type=\"text/javascript\">window.location.href = \"http://locksidian.fries.io/locksidian\"</script></head><body>If you are not redirected automatically, please follow this <a href=\"http://locksidian.fries.io/locksidian\">link</a>.</body></html>" > target/doc/index.html
    - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    - master