image: registry.gitlab.com/locksidian/locksidian-ci:master

services:
  - docker:dind

stages:
  - test
  - build

variables:
  IMAGE_NAME: registry.gitlab.com/locksidian/locksidian:$CI_BUILD_REF_NAME

test:
  stage: test
  script:
    - cargo test

build:
  stage: build
  script:
    - cargo build --release
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME